BoletoNet/BoletoNetCore

- BoletoNetCore.Testes/BoletoNetCore.Testes.csproj
Adicionado netcoreapp3.0 como target framework do projeto BoletoNetCore.Tests.
Por que?
Para que projetos desenvolvidos em netcoreapp3.0, juntamente com
netcoreapp2.0, possuam cobertura de testes.
> Update BoletoNetCore.Tests netcoreapp3.0

- BoletoNetCore/Banco/Siscoob/BancoSicoob.CNAB240.cs
Olá, bom dia.
Abri esse novo PR para ajustar novamente o arquivo de remessa Sicoob CNAB 240.
Testando aqui identifiquei que a coluna que precisa ser preenchida com '0' é a subsequente a digito verificador da conta.
Issue: #37
> Ajuste na geração do header do arquivo de remessa Sicoob CNAB 240

- README.md
Nome do banco Sicredi estava errado no arquivo README.md
> Ajuste no README. Nome do Banco Sicredi

- BoletoNetCore/Banco/Bradesco/BancoBradesco.CNAB240.cs
Ajustes dos erros retornado no processo de homologação com o banco carteira 09 CNAB240, onde estava com discrepância na classe em comparacao com boleto2Net.
> Ajustes Banco  Bradesco Carteira09 CNAB 240

- README.md
> Ajuste no nome do Banco Sicredi

- BoletoNetCore/Banco/Sicredi/BancoSicredi.CNAB400.cs
Alteração referente a essa discussão https://github.com/BoletoNet/boleto2net/issues/214
Já foi implementada no boleto2net
> Preencher campo Numero de Controle do Participante ao ler o retorno (Sicredi)

- BoletoNetCore/Boleto/Endereco.cs
Quando passava um complemento muito grande, a ultima linha desse método dava um erro,
Aqui
`return LogradouroEndereco.Substring(0, tamanhoFinal - logradouroCompleto.Length) + logradouroCompleto;`
Quando o complemento era muito grande, o tamanho de logradouroCompleto ficava maior que tamanhoFinal, e a subtração (tamanhoFinal - logradouroCompleto.Length) dava um número negativo causando o erro.
Ajustei para cortar em no máximo 20 o complemento, com isso o logradouroCompleto não terá mais de 40 caracteres como estava passível de ter antes.
O campo número fiquei na dúvida se faria esse tratamento, pra o meu caso não precisa porque é inteiro e apenas converto pra string.
Alteração já foi feita no boleto2net https://github.com/BoletoNet/boleto2net/pull/217
> Ajuste no método FormataLogradouro

- BoletoNetCore/Banco/Sicredi/BancoSicredi.CNAB400.cs
Ajustado para pegar a data de crédito na posição correta
Conforme o manual página 54 campo Data prevista para lançamento no conta corrente
Foram feitos vários testes e não vem data na posição que estava pegando antes.
É nessa posição 329 a 336 que vem a data.
Alteração já foi feita no boleto2net https://github.com/BoletoNet/boleto2net/pull/218
> Sicredi - Data de Crédito

- BoletoNetCore/Banco/Sicredi/BancoSicredi.CNAB400.cs
No campo multa, assim como outros campos numéricos, precisa ser com duas casas decimais conforme testes que fiz.
Exemplo: ao passar 2 para o campo PercentualMulta, no arquivo era gerado 0002 na posição 093-096
O correto é gerar 0200 com dois zeros a direita para o banco considerar 2% de multa.
*Feito testes reais em produção enviado o arquivo para o banco.
Alteração já foi feita no boleto2net https://github.com/BoletoNet/boleto2net/pull/224
> Ajustado campo multa para duas casas decimais (Sicredi)

- BoletoNetCore/Banco/Sicredi/BancoSicredi.CNAB400.cs
O campo tipo de juros estava "A" (valor),
E na posição 161 está passando o campo PercentualJurosDia
Ajustado tipo de juros para "B" (percentual)
Mesma correção já foi feita no boleto2net https://github.com/BoletoNet/boleto2net/pull/223
> Remessa Sicredi campo Tipo de Juros incorreto

- BoletoNetCore/Banco/Sicredi/BancoSicredi.CNAB400.cs
Ver #99 
Ao gerar remessa Sicredi CNAB 400 estava passando sempre 0 na posição  395 à 400
> Incrementar numero registro Sicredi CNAB400

- BoletoNetCore/Boleto/Boleto.cs
quando cria a instancia de um boleto e o beneficiário é null, acontece na caixa
> erro ao ler remessa quando o beneficiário é null

- BoletoNetCore/Banco/BancoBrasil/BancoBrasil.cs
Não coloca os dígitos de agência e conta corrente no campo CodigoFormatado do Banco do Brasil quando não houver essa informação.
Ex.: Foi utilizado os dados de teste da API de cobrança do Banco do Brasil que não contém dígitos em agência e conta (https://apoio.developers.bb.com.br/referency/post/5ffc477c3b02bd0012ecaa1a)
> Dígitos de Beneficiario.CodigoFormatado

- BoletoNetCore/Banco/Sicredi/BancoSicredi.CNAB240.cs
o manual do sicredi preve o nosso numero da posicao 38 ate 57 (20 caracteres)
contudo, o retorno CNAB240 do sicredi retorna assim: "7480001300005T 0600720 0000000427179 212332573           1DOC1234"
sendo que o valor na possicao do nosso numero seria "212332883           "
há um espacamento em branco no retorno, e a classe base tem feito substring a partir da posicao 8 
assim, está pegando apenas o ultimo digito e o restante espacos em branco
string tmp = registro.Substring(37, 20);
boleto.NossoNumero = tmp.Substring(8, 11);
essa implementação sugere dessa maneira, ou seja, aproveitando a classe base mas alterando a posicao do nosso numero
> ajuste na posicao de leitura do nosso numero no retorno cnab240 sicredi

- BoletoNetCore/Banco/BancoBrasil/Carteiras/BancoBrasilCarteira17.cs
Alteração pra permitir a utilização da carteira 17 com variação 035 no Banco do Brasil
> Acrescentado o código de carteira 17/035

- BoletoNetCore/Banco/BancoBrasil/BancoBrasil.CNAB240.cs
conforme manual disponivel em https://www.bb.com.br/docs/pub/emp/empl/dwn/CbrVer04BB.pdf
"Campo não tratado. Preencher com 'zeros'."
a posição 210 a 212 do segmento P deve ser preenchido com zeros, atualmente estava sendo preenchido com espacos.
> posicao 210 a 212 do segmento Q deve ser preenchido com zeros

- BoletoNetCore/Banco/BancoBrasil/BancoBrasil.cs
O projeto ACBr usa o padrão geral como CBddMMXX.rem
dd = dia com dois digitos
MM = mes com dois dígitos
XX = sequencia
Fiz o ajuste diretamente na classe do banco do brasil, mas deixo como sugestão, posso ate implementar aqui se quiser, colocar isso na classe BancoFebraban<>, assim, a implementação precisaria ser feita apenas para os bancos que tem particularidades no nome do arquivo, como sicredi por exemplo.
> formatar nome do arquivo de remessa para banco do brasil

- BoletoNetCore/Banco/BancoBrasil/BancoBrasil.CNAB240.cs
- BoletoNetCore/Enums/TipoCodigoProtesto.cs
Adicionado NegativacaoSemProtesto no enum TipoCodigoProtesto; Realizado tratamento na remessa CNAB240 do Banco do Brasil para considerar o novo tipo NegativacaoSemProtesto; Manual BB disponível em https://www.bb.com.br/docs/pub/emp/empl/dwn/CNAB240SegPQRSTY.pdf pagina 14 campo 36.3P posicao 221 do segmento P
> Negativação sem Protesto p/ Banco do Brasil Remessa CNAB240

- BoletoNetCore/Banco/Caixa/BancoCaixa.CNAB400.cs
- BoletoNetCore/Banco/Caixa/BancoCaixa.cs
- BoletoNetCore/Boleto/Boleto.cs
Quando for gerado o arquivo de remessa utilizando um código do beneficiário de 7 digitos, é necessário incluir o valor "007" na posição 101 - 103
O prazo para baixa automática do boleto esta zerada, então defini o máximo "99" e deixando a possibilidade para preenchimento da variável "DiasLimiteRecebimento"  para personalização.
> Caixa (104) - Ajuste no arquivo de remessa para beneficiário de 7 digitos e no prazo de recebimento que esta zerado.

- BoletoNetCore.QuestPdf/Carne/ReciboLateralCarne.cs
- BoletoNetCore/Banco/Itau/BancoItau.CNAB400.cs
- BoletoNetCore/Banco/Itau/Carteiras/BancoItauCarteira157.cs
Estou usando o BoletoNetCore para fazer o CNAB400 do Itau, e no meu caso, aplico um prazo de 10 dias de protesto, mas no arquivo [BancoItau.CNAB400.cs](https://github.com/BoletoNet/BoletoNetCore/blob/master/BoletoNetCore/Banco/Itau/BancoItau.CNAB400.cs), na linha 113, ele está passando 0 nesse registro, na hora de preencher a posição 392 e 393.
Neste caso a propriedade `boleto.DiasProtesto` poderia fazer este papel tal qual está fazendo em outros layouts. Como essa parte de protesto é bem incomum de ser usada, acho que quem usava contava com o padrão de sempre (causando se não me engano 2 dias úteis de prazo)
De acordo com o manual... 
**TL;DR**
Posição 392 e 393 do detalhe de remessa está sendo sempre preenchida com 0 no CNAB400 do Itau. Trocado para usar boleto.DiasProtesto.
> CNAB400 Itau - campo de prazo zerado

- BoletoNetCore/Banco/Siscoob/BancoSicoob.CNAB240.cs
- BoletoNetCore/Banco/Siscoob/Carteiras/BancoSincoobCarteira1.cs
Fiz algumas alterações no banco Sicoob.
1 - Ao gerar o segmento P do arquivo de remessa, não estava considerando o juros caso fosse por percentual, apenas por valor.
2 - Ao gerar o segmento R do arquivo de remessa, não estava considerando a multa caso fosse por percentual, apenas por valor.
> Alterações Juros/Multa/NossoNumero Sicoob

- BoletoNetCore/Banco/Sicredi/BancoSicredi.CNAB240.cs
devido aos ajustes para não concatenação do digito verificador ao nosso numero, foi necessario realizar o ajuste na leitura de retorno
> Ajuste p/ Leitura de Retorno Sicredi CNAB 240

- BoletoNetCore/Banco/Itau/BancoItau.CNAB400.cs
Ajuste para preencher o campo data mora da remessa com a data do juros ou data de vencimento, antes estava sempre preenchendo com 0.
> Ajuste para informar a data do juros na remessa.

- BoletoNetCore.Testes/BancoItauCarteira138Tests.cs
- BoletoNetCore/Banco/Itau/Carteiras/BancoItauCarteira138.cs
Implementar a carteira 138 do banco Itaú. Essa carteira é destinada aquelas empresas que optaram pelo banco realizar a impressão e envio dos boletos. Mais detalhes da implementação clicando [aqui](https://download.itau.com.br/bankline/layout_cobranca_400bytes_cnab_itau_mensagem.pdf).
Já estou utilizando essa versão em meu ambiente de produção para enviar os boletos através do WhatsApp e tem funcionado muito bem.
E-mail: lucianfiocello@gmail.com
Desde já agradeço muito pelo trabalho que vocês realizaram até aqui, ainda estou iniciando e pretendo evoluir o boleto em Linux.
Peço desculpas se eu estiver errando na forma como contribuir, é minha primeira contribuição.
Cordialmente,
Lucian Rezende
> Carteira 138 - implementação e testes

- BoletoNetCore/Banco/Bradesco/Carteiras/BancoBradescoCarteira02.cs
- BoletoNetCore/Banco/Bradesco/Carteiras/BancoBradescoCarteira05.cs
- BoletoNetCore/Banco/Bradesco/Carteiras/BancoBradescoCarteira09.cs
- BoletoNetCore/Banco/Bradesco/Carteiras/BancoBradescoCarteiraBase.cs
- BoletoNetCore/Banco/Cecred/BancoCecred.CNAB400.cs
refactoring na implementacao das carteiras do bradesco para remover duplicidade de codigo; no caso em questao, as carteiras 05 e 09 existentes, possuiam o mesmo codigo duplicado, foi criado uma classe base abstrata para ser herdado por elas, alem disso, adicionado a carteira 02 nos mesmos moldes das outras duas
> Carteira 02 Bradesco

- BoletoNetCore/Banco/BancoBrasil/BancoBrasil.CNAB240.cs
- BoletoNetCore/Util/Cnab.cs
- Ajuste para preencher o código do beneficiário ao ler retorno CNAB240.
- Ajuste para limpar o nome do pagador quando ele for tudo 00000... Pelo que vi o Banco do Brasil não retorna os dados do pagador no arquivo de retorno CNAB240.
- Adicionado código de movimento retorno 11 - Títulos em Carteira (em ser),
> CNAB 240 - Banco do Brasil

- BoletoNetCore/BoletoImpressao/Parts/ReciboBeneficiarioParte10.html
Alteração da nomenclatura de Pagador Avalista para Beneficiário final - (Obs: No boleto físico, o termo Avalista foi substituído por Beneficiário final, conforme Convenção entre Instituições do Sistema Financeiro Nacional FB-0061/2021"). 
**Essa mudança foi necessária após eu homologar com banco safra carteira 1, pediram essa modificação.**
Links Externos:
https://www.projetoacbr.com.br/forum/topic/64334-problemas-para-homologar-boleto-safra-fastreport/
> Beneficiário final - Convenção entre Instituições do Sistema Financeiro Nacional FB-0061/202

- BoletoNetCore/Util/Utils.cs
Causando erro..
O correto é se for vazio, ele não formatar e ignorar (retornando ele mesmo).
> arrumado erro de cpf/cnpj vazio dando erro ao formatar

- BoletoNetCore/Banco/Itau/BancoItau.CNAB240.cs
Registro: header
Linha: 1
Posição 033 - Campo: Complemento de Registro - Conteúdo deve estar em branco. (155599496 )
Correção: Preencher com espaço em branco
Posição 103 - Campo: Nome por Extenso do Banco Cobrador - Conteúdo fixo difere do esperado. (BANCO ITAU )
Correção: Preencher com BANCO ITAU SA
Posição 226 - Campo: Complemento de Registro - Conteúdo não é igual a zeros. (em branco)
Correção: Preencher com 0 em vez de espaço em branco
Layout: CNAB 240 - Cobrança Detalhe P
Registro: detalhe
Linha: 3
Posição 101 - Campo: Agência onde o Título será Cobrado - Conteúdo não é igual a zeros. (em branco)
Correção: Preencher com 0 em vez de espaço em branco
Posição 106 - Campo: Dígito de Auto-Conferência Agência Cobradora - Conteúdo não é igual a zeros. (2)
Correção: Preencher com 0 em vez de …
>  Correções realizadas para atender o validador do Itau seguindo o manual CNAB240

- BoletoNetCore/Banco/BancoBrasil/BancoBrasil.CNAB240.cs
Tivemos alguns a entradas de boletos rejeitados quando os mesmos tinham desconto.
Enviamos a data e valor do desconto  do desconto1 nos campos desconto2 e desconto3.  IMPORTANTE( Orientados pelo validador do banco de Brasil). Porém em produção a orientação causou rejeições. 
Agora a data e valor dos descontos 2 e 3 é sempre preenchido com zeros, utilizando esta abordagem já efetuamos envios e retornos em produção e ambos com sucesso.
> Correções e melhorias no segmento R nos campos desconto2 e desconto3.

- BoletoNetCore/Banco/BancoBrasil/BancoBrasil.CNAB240.cs
ao gerar uma remessa de boleto com desconto no banco do brasil, está sendo recusado devido aos campos Codigo do Desconto 2 e Codigo do Desconto 3, que estavam sendo tratados conforme a propriedade ValorDesconto, mas como os valores destes campos sao passados zerados na remessa, o código deve ser zero tambem, conforme o manual do banco
> Boleto Banco do Brasil Recusado quando há desconto

- BoletoNetCore/Banco/Sicredi/BancoSicredi.CNAB400.cs
- Leitura do Header CNAB400 da Caixa estava somente validando tipo de arquivo.
- Adicionado controle para pegar dados do Header conforme manual da SICREDI.
- Somente o Código do Cedente. (Mas já é uma informação importante para fazer validação de dados se o arquivo remessa é correspondente ao banco de importação em questão).
> Adicionada Leitura do Header Retorno CNAB400 SICREDI.

- BoletoNetCore/Banco/Caixa/BancoCaixa.CNAB240.cs
- Leitura do Header CNAB240 da Caixa estava em branco (somente com comentários) fazendo com que não lesse nenhum informação do cabeçalho do arquivo retorno.
- Adicionado controle para pegar dados do Header conforme manual da CAIXA.
> Correção: Leitura do Header Retorno CNAB240 Caixa.

- BoletoNetCore/Banco/BancoBrasil/BancoBrasil.CNAB400.cs
- CNAB400 do Banco do Brasil estava utilizando método herdado na leitura da header, que trazia os dados de modo genérico sem as divisões que ele possui.
- Criado override para leitura dos dados da Header conforme informações do arquivo retorno.
- Leitura do Convênio (Código do Beneficiário) com Trim() para suportar arquivos antigos (que vinha em branco).
> Adicionada Leitura do Header Retorno CNAB400 Banco do Brasil.

- BoletoNetCore/Banco/Sicredi/BancoSicredi.CNAB400.cs
- Descrições das Ocorrências cadastrados no CNAB400 da SICREDI era de outro banco.
- Corrigido com os dados correntes contidos no manual da SICREDI.
- Corrigidas nomenclaturas conforme manual da SICREDI.
- Link para conferência: [https://www.sicredi.com.br/media/produtos/manual_cnab_400_2_1.pdf](url) (Página 17 - Item 7.2)
> Correção das Descrições de Ocorrências do CNAB400 da SICREDI.

- BoletoNetCore.Pdf/BoletoNetCorePdfProxy.cs
- BoletoNetCore.Testes/ExemploClasseProxy.cs
- BoletoNetCore/BoletoNetCoreProxy.cs
Inclusão do parâmetro opcional **_pixString_** no método **_GerarBoletos_** para permitir a geração de boletos híbridos com QRCode Pix.
` public virtual bool GerarBoletos(string nomeArquivo, ref string mensagemErro, string pixString = null)`
Exemplo do boleto gerado:
> Obs.: Os dados da imagem acima foram ocultados por questões confidenciais.
> Inclusão de parâmetro no metodo GerarBoletos para inclusão de QrCode nos boletos

- BoletoNetCore/Boleto/CodigoBarra.cs
- BoletoNetCore/BoletoNetCore.csproj
Com o advento das APIs "developers" dos bancos para a cobrança, muitos devolvem o código de barras como ele deve ser impresso no boleto.
Com isso, não há a necessidade de se criar o código de barras uma vez que ele foi informado
> A propriedade código de barras pode aceitar valor.

- BoletoNetCore/Banco/Sicoob/BancoSicoob.CNAB400.cs
- BoletoNetCore/Banco/Sicoob/BancoSicoob.cs
o Cnab 400 esta sendo descontinuado e a conta esta limitada a 8 dígitos sendo que o Cnab240 tem ate 12 dígitos sendo assim alterei a quantidade limite para 12
> Conta do Siccob pode ter ate 12 dígitos

- BoletoNetCore/Arquivo/ArquivoRemessa.cs
O Erro estava na execução duplicada do método `GerarMensagemRemessa` sendo gerado a numeração de linha com falha
> fix: na chamada do método `GerarMensagemRemessa`

- .gitignore
- BoletoNetCore/Banco/BancoBrasil/BancoBrasil.CNAB400.cs
O CNAB 400 do banco do brasil não estava validando multa pelo campo de percentual. Apenas por valor. Adicionada validação para tal.
Adicionado ao .gitignore os arquivos .DS_Store que o macos gera em todas as pastas do sistema.
> Validação de valor e percentual de multa no banco do brasil cnab 400

- BoletoNetCore/Banco/Itau/BancoItau.CNAB400.cs
Estou utilizando para ler alguns retornos de arquivos CNAB400 do Itaú, e tive um problema com arquivos como esse em anexo.
As posições de alguns campos de valor estavam em branco, fazendo o Convert para Decimal causar Exception "System.FormatException: The input string '' was not in a correct format."
[P0010108.000000000.txt](https://github.com/user-attachments/files/16473752/P0010108.000000000.txt)
> Espaços em branco nas posi' valores na conversão para decimal em arquivos retorno ITAU

- BoletoNetCore.QuestPdf/Carne/ReciboLateralCarne.cs
Ajuste no campo "Parcela" na geração de PDF para usar o campo "parcelaInformativo" do boleto ao invés de usar o valor fixo "001 /001", semelhante ao que é feito para Html.
> Ajuste do campo "Parcela" no pdf

- BoletoNetCore/Enums/TipoEspecieDocumento.cs
O banco Itau define a especie documento 99 que geralmente é outros (OU) como diversos (DV). Portanto para que o campo especie documento possa ter o valor DV utilizado no Itau, estou adicionando esse novo valor de enum.
> Inclui novo TipoEspecieDocumento

- BoletoNetCore.Testes/Bancos/Bradesco/Carteiras/BancoBradescoCarteira09.cs
- BoletoNetCore/Arquivo/ArquivoRetorno.cs
- BoletoNetCore/Banco/BancoBrasil/BancoBrasil.CNAB400.cs
- BoletoNetCore/Banco/BancoInter/BancoInter.CNAB400.cs
- BoletoNetCore/Banco/Banrisul/BancoBanrisul.CNAB400.cs
- BoletoNetCore/Banco/Bradesco/BancoBradesco.CNAB400.cs
- BoletoNetCore/Banco/Bradesco/BancoBradesco.cs
- BoletoNetCore/Banco/Caixa/BancoCaixa.CNAB400.cs
- BoletoNetCore/Banco/Cecred/BancoCecred.CNAB400.cs
- BoletoNetCore/Banco/CrediSis/BancoCrediSIS.CNAB400.cs
- BoletoNetCore/Banco/Daycoval/BancoDaycoval.CNAB400.cs
- BoletoNetCore/Banco/IBanco.cs
- BoletoNetCore/Banco/Itau/BancoItau.CNAB400.cs
- BoletoNetCore/Banco/Safra/BancoSafra.CNAB400.cs
- BoletoNetCore/Banco/Santander/BancoSantander.CNAB400.cs
- BoletoNetCore/Banco/Sicoob/BancoSicoob.CNAB400.cs
- BoletoNetCore/Banco/Sicredi/BancoSicredi.CNAB400.cs
- BoletoNetCore/Banco/UniprimeNortePR/BancoUniprimeNortePR.CNAB400.cs
- BoletoNetCore/Boleto/Boleto.cs
Segue sugestão de PR da implementação da leitura do segmento 4 para retorno do layout 400 Bradesco. Esse segmento é usado para boleto híbridos, onde vem o qrcode gerado automaticamente pelo banco. No arquivo de remessa não há alteração, pois isso é um configuração feita apenas pelo banco. Aprovei e adicionei alguns testes de retorno também. 
Sobre os campos criados na classe boleto, tentei seguir o padrão do projeto BoletoNet, onde já existe uma propriedade chamada 'QrCode'.
Segue layout:
> Implementado leitura de segmento 4 para layout 400.

- BoletoNetCore.Testes/Bancos/Santander/Carteiras/BancoSantanderCarteira101Tests.cs
- BoletoNetCore/Arquivo/ArquivoRetorno.cs
- BoletoNetCore/Banco/BancoBrasil/BancoBrasil.CNAB400.cs
- BoletoNetCore/Banco/BancoInter/BancoInter.CNAB400.cs
- BoletoNetCore/Banco/Banrisul/BancoBanrisul.CNAB400.cs
- BoletoNetCore/Banco/Bradesco/BancoBradesco.CNAB400.cs
- BoletoNetCore/Banco/Caixa/BancoCaixa.CNAB400.cs
- BoletoNetCore/Banco/Cecred/BancoCecred.CNAB400.cs
- BoletoNetCore/Banco/CrediSis/BancoCrediSIS.CNAB400.cs
- BoletoNetCore/Banco/Daycoval/BancoDaycoval.CNAB400.cs
- BoletoNetCore/Banco/IBanco.cs
- BoletoNetCore/Banco/Itau/BancoItau.CNAB400.cs
- BoletoNetCore/Banco/Safra/BancoSafra.CNAB400.cs
- BoletoNetCore/Banco/Santander/BancoSantander.CNAB400.cs
- BoletoNetCore/Banco/Santander/BancoSantander.cs
- BoletoNetCore/Banco/Sicoob/BancoSicoob.CNAB400.cs
- BoletoNetCore/Banco/Sicredi/BancoSicredi.CNAB400.cs
- BoletoNetCore/Banco/UniprimeNortePR/BancoUniprimeNortePR.CNAB400.cs
- BoletoNetCore/Boleto/ContaBancaria.cs
- BoletoNetCore/Enums/TipoChavePix.cs
Segue sugestão de PR com implementação do boleto hibrido com layout 400 para o banco Santander.
Para isso foi adicionado 2 propriedades na entidade ContaBancaria, sendo que na remessa se a propriedade "ChavePix"  for preenchida, será gerado o segmento 8.
No retorno, foi implementado a leitura do segmento 2.
Por fim, adicionei testes na remessa e retorno para esse layout. 
[Link layout do banco](https://cms.santander.com.br/sites/WPS/documentos/arq-layout-de-arquivos-download-cob400ptbr/25-05-06_134057_cobranca-353_400+posi%C3%A7%C3%B5es-v.+2.35-abril-2024-ptbr.pdf)
> Remessa e retorno boleto híbrido Santander

- BoletoNetCore/Banco/Safra/BancoSafra.CNAB400.cs
- Corrigido mapeamento do campo "Valor Pago" no retorno CNAB 400 do Banco Safra
- Antes o valor estava sendo atribuído a ValorPagoCredito, o que não está de acordo
com o manual do banco e gerava inconsistência
- Agora o campo correto ValorPago é preenchido, garantindo compatibilidade com o manual do Safra
> #373-Ajuste no CNAB 400 do Banco Safra para preencher ValorPago corretamente.
