BoletoNet/BoletoNetCore

BoletoNetCore/Banco/Carteiras/BancoSicredi/BancoSicrediCarteira1.cs

https://github.com/BoletoNet/BoletoNetCore/issues/4

Ajustando testes sicredi

---

BoletoNetCore.Pdf/BoletoNetCore.Pdf.csproj
BoletoNetCore/BoletoNetCore.csproj

dos projetos 
- BoletoNetCore 
- BoletoNetCore.Pdf

Gerando pacotes automaticamente na build 

---

README.md

Documentação sobre pacote distinto para impressão em PDF

---

README.md

corrigido link para nuget do pacote BoletoNetCore.PDF

Correção do link externo que não existia anteriormente

---

BoletoNetCore/Banco/Siscoob/BancoSicoob.CNAB240.cs

Alteração no preenchimento do digito verificador da conta no arquivo de remessa do Sicoob CNAB240.
Issue: #37

Arquivo remessa Sicoob (Preenchimento DV Conta - CNAB 240)

---

BoletoNetCore.Testes/Utils.cs
BoletoNetCore/Banco/Bradesco/BancoBradesco.CNAB400.cs
BoletoNetCore/Boleto/Boleto.cs

Foram adicionados os atributos que antes eram passados em branco, para a geração do arquivo Cnab.

Implementações Faltantes no Layout Bradesco Cnab 400 

---

BoletoNetCore.Testes/BancoSicrediCarteira1Tests.cs
BoletoNetCore/Extensions/DateTimeExtensions.cs

Corrigido Bug nos testes. Nosso 2 primeiros digitos do Nosso Número é igual ao Ano da Data de Emissâo.
Aumentado o limite no fator de vencimento.

Bug Fix Testes

---

BoletoNetCore/BoletoImpressao/BoletoBancario.cs

Foi adicionado e extensão html na função GeraCarne
Issue: https://github.com/BoletoNet/BoletoNetCore/issues/52

Foi adicionado extensão html para uso do formato carne

---

BoletoNetCore/Banco/Bradesco/Carteiras/BancoBradescoCarteira05.cs

Foi adicionado a carteira 05, ela tem o mesmo comportamento da carteira 09.

Adicionado Carteira 05 Bradesco.

---

BoletoNetCore/Banco/Itau/BancoItau.CNAB400.cs
BoletoNetCore/Banco/Itau/Carteiras/BancoItauCarteira153.cs

Adicionado carteira 153 banco Itaú.

Carteira 153 - Itaú

---

BoletoNetCore/Arquivo/ArquivoRemessa.cs
BoletoNetCore/Arquivo/ArquivoRetorno.cs
BoletoNetCore/Banco/BancoFebraban.CNAB240.cs
BoletoNetCore/Banco/BancoFebraban.cs
BoletoNetCore/Banco/IBanco.cs
BoletoNetCore/Banco/Itau/BancoItau.CNAB240.cs
BoletoNetCore/Boleto/Boleto.cs
BoletoNetCore/Enums/TipoCarteira.cs
BoletoNetCore/Enums/TipoJuros.cs
BoletoNetCore/Enums/TipoMoeda.cs

Implementação para escrita e leitura do cnab 240 itau segmento A.

Itau 240 Cnab Segmento A

---

BoletoNetCore/Banco/Banco.cs
BoletoNetCore/Banco/Safra/BancoSafra.CNAB400.cs
BoletoNetCore/Boleto/Boleto.cs

https://github.com/BoletoNet/BoletoNetCore/issues/93
https://github.com/BoletoNet/BoletoNetCore/pull/91

[Safra - CNAB400] - Informações de multa na remessa bancária 

---

BoletoNetCore.sln
BoletoNetCore/Arquivo/ArquivoRemessa.cs
BoletoNetCore/Banco/BancoFebraban.cs
BoletoNetCore/Banco/IBanco.cs
BoletoNetCore/Banco/Santander/BancoSantander.CNAB150.cs
BoletoNetCore/Banco/Santander/BancoSantander.cs
BoletoNetCore/Banco/Santander/Carteiras/BancoSantanderCarteira1.cs
BoletoNetCore/Banco/Siscoob/BancoSicoob.CNAB150.cs
BoletoNetCore/Banco/Siscoob/Carteiras/BancoSicoobCarteira2.cs
BoletoNetCore/Enums/TipoArquivo.cs

Geração de arquivos cnabs 150 Santander e Sicoob.

Features Cnab150 Santander e Sicoob

---

BoletoNetCore/Banco/Sicredi/BancoSicredi.CNAB400.cs

Ajuste referente a essa discussão https://github.com/BoletoNet/boleto2net/issues/214
É igual a alteração feita no boleto2net

Ajuste para gerar numero do documento no arquivo de remessa

---

BoletoNetCore/Banco/Sicredi/BancoSicredi.CNAB400.cs
BoletoNetCore/Util/Cnab.cs

Não estava carregando as ocorrências para o Banco Sicredi
Adicionado mais motivos para listagem

Motivo da ocorrência

---

BoletoNetCore/Banco/Santander/BancoSantander.CNAB150.cs

Correção para o envio correto do tipo para o banco.

refactor cpf tipo 2 e cnpj tipo 1. Conforme documentacao v5.

---

BoletoNetCore/Banco/Safra/BancoSafra.CNAB400.cs
BoletoNetCore/Banco/Sicredi/BancoSicredi.CNAB400.cs

Remesa de testes corrigida:
```
01REMESSA01COBRANCA       8530586875666000109                               748SICREDI        20210520        0000001                                                                                                                                                                                                                                                                                 2.00000001
1AAA            AAB                            212000021      20210520 N B0000    00000010000200            01BB000001A 2006210000000010000          N200521000000000000000202006210000000001000000000000000000000000000002071738978000101PAGADOR TESTE PJ                        AVENIDA TESTANDO                        00000000000 1234567800000 …
```

[Sicredi][-] Auto incremento

---

BoletoNetCore.Testes/BancoSicrediCarteira1Tests.cs
BoletoNetCore/Banco/Sicredi/BancoSicredi.CNAB240.cs
BoletoNetCore/Banco/Sicredi/BancoSicredi.CNAB400.cs
BoletoNetCore/Banco/Sicredi/BancoSicredi.Online.cs
BoletoNetCore/Util/Extensions.cs

Criado a remessa CNAB240 para o sicredi, nos moldes do projeto ACBr.

Sicredi cnab240

---

BoletoNetCore/Banco/BancoBrasil/BancoBrasil.CNAB400.cs
BoletoNetCore/Boleto/Boleto.cs

https://github.com/BoletoNet/BoletoNetCore/issues/127

[BB - CNAB400] - Dias limite para recebimento

---

BoletoNetCore.Testes/Utils.cs

Ajuste gerar código transmissão remessa Santander Carteira 101 CNAB240

---

BoletoNetCore/Banco/BancoBrasil/BancoBrasil.CNAB400.cs

https://github.com/BoletoNet/BoletoNetCore/issues/127

[-] BB Cnab400 - DiasLimiteRecebimento contem 3 dígitos e não 2

---

BoletoNetCore.Testes/BancoCaixaCarteiraSig14Tests.cs
BoletoNetCore/Banco/Caixa/BancoCaixa.CNAB240.cs
BoletoNetCore/Banco/Caixa/BancoCaixa.cs
BoletoNetCore/Banco/Caixa/Carteiras/BancoCaixaCarteiraSIG14.cs

Feito baseado nas alterações para o Boleto2Net 
[Pull Request](https://github.com/BoletoNet/boleto2net/pull/330)

ajustado remessa da caixa com código beneficiário de 7 digitos

---

BoletoNetCore.Testes/Utils.cs
BoletoNetCore/Boleto/Boleto.cs
BoletoNetCore/BoletoImpressao/BoletoBancario.cs
BoletoNetCore/BoletoImpressao/Parts/ReciboBeneficiarioParte9.html

contém exemplo de uso no Testes Util

Adicionado informativo de parcelas nos boletos  ex : 1/10, 2/10

---

BoletoNetCore/Banco/Sicredi/BancoSicredi.CNAB400.cs

Precisei desse motivo , e reparei que nao continha no arquivo de CNAB400 do Sicredi

Adicionado tarifa conforme manual CNAB400 Sicredi

---

BoletoNetCore/Banco/Sicredi/BancoSicredi.CNAB240.cs
BoletoNetCore/Banco/Sicredi/BancoSicredi.Online.cs
BoletoNetCore/Banco/Sicredi/Carteiras/BancoSicrediCarteira1.cs

Teste unitários passaram normal, exceto o Online pq não tenho chave da API, estou trabalhando somente com troca de arquivos

SICREDI: Ajustes no NossoNumero e NossoNumeroDV

---

BoletoNetCore/BoletoImpressao/BoletoBancario.cs

Descricao: Adicionado a funcao FormataCPFCPPJ na hora de fazer o html pro boleto fisico ser gerado pra aparcer o CNPJ/cpf formatado

Task: Issue - CNPJ formatado no boleto #196

---

BoletoNetCore/Banco/Itau/BancoItau.CNAB400.cs

- Ajuste para listar os motivos de ocorrências no cnab400
- Add descrição ocorrência 29 - Tarifa de Manutenção de Título Vencido

Ajustes na implementação do CNAB 400 - Itaú.

---

BoletoNetCore.Testes/BancoUniprimeNortePRCarteira09Tests.cs
BoletoNetCore/Banco/Banco.cs
BoletoNetCore/Banco/Bancos.cs
BoletoNetCore/Banco/UniprimeNortePR/BancoUniprimeNortePR.cs
BoletoNetCore/Banco/UniprimeNortePR/Carteiras/BancoUniprimeNortePRCarteira09.cs
BoletoNetCore/Extensions/StringExtensions.cs

Boa tarde @carloscds 
Tive um cliente que precisou da emissão de boletos para uniprime entao implementei o basico aqui... falta ainda fazer a remessa, no caso do meu cliente é o cnab400... mas ainda nao tive tempo de implmentar, devo fazer nas proximas semanas..
A emissão do boleto em si ta ok

implementacao do banco uniprime norte pr carteira 9

---

BoletoNetCore/Banco/Safra/BancoSafra.cs
BoletoNetCore/Banco/Safra/Carteiras/BancoSafraCarteira1.cs
BoletoNetCore/Exceptions/BoletoNetCoreException.cs

Foi feito melhoria que esta no boletone2, testado em produção com retorno positivo do banco SAFRA

melhoria e validacao de dados do SAFRA Carteira 1

---

BoletoNetCore/Banco/Bradesco/BancoBradesco.CNAB400.cs

Havia um equivoco no captura da informações de agencia, conta e digito.

Ajustes  Bradesco CompletarHeaderRetornoCNAB400

---

BoletoNetCore/Banco/Banco.cs
BoletoNetCore/Banco/CrediSis/BancoCrediSIS.CNAB240.cs
BoletoNetCore/Banco/CrediSis/BancoCrediSIS.CNAB400.cs
BoletoNetCore/Banco/CrediSis/BancoCrediSIS.cs
BoletoNetCore/Banco/CrediSis/Carteiras/BancoCrediSISCarteira18.cs
BoletoNetCore/Banco/Siscoob/Carteiras/BancoSincoobCarteira1.cs
BoletoNetCore/Boleto/ContaBancaria.cs
BoletoNetCore/Util/Utils.cs
README.md

Implementado banco CrediSIS - 097 - Carteira 018 - CNAB240 - Remessa bancária

Implementado banco CrediSIS CNAB240

---

BoletoNetCore/Banco/BancoBrasil/BancoBrasil.CNAB240.cs

- CNAB240 permite utilização do percentual de Multa na Remessa.
- Adicionada verificação do tipo de multa na Remessa CNAB240 do BB.

Correção: Adicionado Percentual de Multa na Remessa CNAB240 BB

---

BoletoNetCore/Banco/BancoFebraban.cs
BoletoNetCore/Banco/IBanco.cs
BoletoNetCore/Banco/Itau/BancoItau.CNAB400.cs

Implementação da leitura do arquivo de retorno do Itaú (CNAB400) referente a desconto de boletos, o Itaú trata em arquivo separado.

Implementação do desconto de boletos do Itaú.

---

BoletoNetCore.Testes/Bancos/Bradesco/Carteiras/BancoBradescoCarteira04.cs
BoletoNetCore/Banco/Bradesco/Carteiras/BancoBradescoCarteira04.cs

Realizado implementação da carteira bancaria 04 do banco Bradesco.

Implementado carteira bancaria 04 do banco bradesco

---

BoletoNetCore/Banco/Cecred/Carteiras/BancoCecredCarteira1.cs

#281 - Feito alteração no fonte.

#281 - Ajustado nosso numero formatado para a impressao do boleto Ailos

---

BoletoNetCore.Testes/Bancos/Santander/Carteiras/BancoSantanderCarteira101Tests.cs
BoletoNetCore/Banco/Santander/BancoSantander.CNAB400.cs

Implementar Cnab 400 do Santander

Implementar Cnab 400 do Santander

---

BoletoNetCore.Testes/Bancos/Santander/Carteiras/BancoSantanderCarteira101Tests.cs
BoletoNetCore/Banco/Santander/BancoSantander.CNAB400.cs
BoletoNetCore/Banco/Sicredi/BancoSicredi.CNAB240.cs
BoletoNetCore/Banco/Sicredi/Carteiras/BancoSicrediCarteira1.cs
BoletoNetCore/Boleto/Boleto.cs

Correção de Santander 400 e campo para o Byte do numero de remessa do Sicredi

Fix santander400

---

BoletoNetCore/Banco/Sicoob/BancoSicoob.cs

Ajustado mensagem de local de pagamento do banco sicoob

#321 - Ajustado mensagem de local de pagamento do banco sicoob

---

BoletoNetCore/Banco/BTGPactual/BancoBTGPactual.cs
BoletoNetCore/Banco/BTGPactual/Carteiras/BancoBTGPactualCarteira01.cs
BoletoNetCore/Extensions/StringExtensions.cs

Verifiquei que havia um erro na formação da linha digitável. Foi conferido e testado com diversos boletos registrados por outras ferramentas e todos gerados corretamente.

Correção na linha digitável BTG Pactual

---

BoletoNetCore/Banco/BancoInter/Carteiras/BancoInterCarteira112.cs
README.md

Olá,
implementado carteira 112 do inter, com emissão pelo banco

Inter carteira112

---

BoletoNetCore/Banco/Sicoob/Carteiras/BancoSicoobCarteira1.cs
BoletoNetCore/Boleto/Boleto.cs

ajuste numero parcela na linha digitavel boleto sicoob

ajuste linha digitavel com numero parcela

---

BoletoNetCore/BoletoImpressao/Parts/GrupoDemonstrativo.html

Implementa grupo demonstrativo assim como do projeto BoletoNet.

Implementa grupo demonstrativo

---

BoletoNetCore/Banco/BancoFebraban.cs
BoletoNetCore/Banco/CarteiraFactory.cs
BoletoNetCore/Banco/IBanco.cs

Ignore os commits com `*.Packages updates.*`, são atualizações de pacotes que eu faço, semanalmente.
O importante, são os commits marcados com `#region #173339 - Remover no Pull Request (se aprovado)`
Segue o link direto do commit: [d785ffce6af1232cdc388562a940f9a0ee1fac25](https://github.com/marcelo-unimake/BoletoNetCore/commit/d785ffce6af1232cdc388562a940f9a0ee1fac25)

Implementação de método ObterCarteiras(). ID #173339
